### ISSUE TITLE
Získávat presenter už v konstruktoru z Application je špatně, protože se může v průběhu requestu změnit

### ISSUE THREAD

**Issue by fprochazka** [iPublikuj/WidgetsManager#1]
https://github.com/iPublikuj/WidgetsManager/blob/27244e640235589efa20e12081ecbbbf04109deb/src/IPub/WidgetsManager/WidgetsProvider.php#L65

**Comment by akadlec** [comment]
Díky za podnět, sice sem si toho všim až teď ;) ale už je to přepracované
